name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
env:
  LANG: "fr_FR.UTF-8"
jobs:
    build:
        runs-on: ubuntu-latest

        steps:

        - name: fr_FR.UTF-8
          run: |
              sudo locale-gen fr_FR.UTF-8
              sudo update-locale LANG=fr_FR.UTF-8

        - name: date
          run: |
              date

        - uses: actions/checkout@v1

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install pelican with markdown
          shell: bash
          run: "pip install invoke pelican[markdown]"

        - name: Set up pelican and dependencies
          shell: bash
          run: "pip install -r requirements.txt"

        - name: Get the pagefind binary
          shell: bash
          run: "wget https://github.com/CloudCannon/pagefind/releases/download/v0.12.0/pagefind-v0.12.0-x86_64-unknown-linux-musl.tar.gz"

        - name: Extract pagefind binary
          shell: bash
          run: "tar -xvzf pagefind-v0.12.0-x86_64-unknown-linux-musl.tar.gz"

        - name: Build the project
          shell: bash
          run: "pelican content -o output -s publishconf.py"

        - name: Create pagefind index
          shell: bash
          run: "./pagefind_index.sh"

        - name: Check if we have everything
          shell: bash
          run: "ls -la output/"

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: output # The folder the action should deploy.
